version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    restart: always
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - postgres
      - redis
      - product-service
    ports:
      - "8082:8082"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
